export const mangoRecipes = [
  // 🟢 UNRIPE (RAW MANGO)
  ...[
    "Raw Mango Pickle",
    "Aam Ka Achaar",
    "Raw Mango Chutney",
    "Kairi Pudina Chutney",
    "Raw Mango Dal",
    "Kairi Rice",
    "Raw Mango Salad",
    "Kairi Panha",
    "Raw Mango Curry",
    "South Indian Mango Rasam",
    "Raw Mango Sambar",
    "Kairi Paratha",
    "Raw Mango Thepla",
    "Green Mango Salsa",
    "Raw Mango Soup",
    "Kairi Sabzi",
    "Raw Mango Stir Fry",
    "Kairi Chaat",
    "Raw Mango Pickle Oil Fry",
    "Spicy Raw Mango Relish"
  ].map(name => ({
    name,
    type: "savory",
    suitableFor: ["unripe"],
    varieties: ["Totapuri", "Dasheri"],
    steps: [
      "Peel and chop raw mango",
      "Add spices and seasoning",
      "Cook or mix as required",
      "Serve fresh"
    ]
  })),

  // 🟡 PERFECT RIPE (MAIN CATEGORY)
  ...[
    "Mango Shake",
    "Aamras",
    "Mango Lassi",
    "Mango Smoothie",
    "Mango Juice",
    "Mango Milkshake Deluxe",
    "Mango Ice Cream",
    "Mango Kulfi",
    "Mango Cheesecake",
    "Mango Mousse",
    "Mango Pudding",
    "Mango Tart",
    "Mango Pancakes",
    "Mango Waffles",
    "Mango French Toast",
    "Mango Salad",
    "Mango Yogurt Bowl",
    "Mango Oatmeal",
    "Mango Chia Pudding",
    "Mango Sorbet",
    "Mango Gelato",
    "Mango Cream Dessert",
    "Mango Falooda",
    "Mango Rabdi",
    "Mango Custard",
    "Mango Sandwich",
    "Mango Bruschetta",
    "Mango Salsa",
    "Mango Wrap",
    "Mango Rice Sweet",
    "Mango Kheer",
    "Mango Modak",
    "Mango Barfi",
    "Mango Halwa",
    "Mango Smoothie Bowl",
    "Mango Protein Shake",
    "Mango Energy Bowl",
    "Mango Popsicles",
    "Mango Lemonade",
    "Mango Mint Cooler",
    "Mango Mojito",
    "Mango Soda",
    "Mango Iced Tea",
    "Mango Mocktail",
    "Mango Punch",
    "Mango Spritzer",
    "Mango Fruit Bowl",
    "Mango Granola Bowl",
    "Mango Cake Slice",
    "Mango Muffins"
  ].map(name => ({
    name,
    type: "dessert",
    suitableFor: ["perfect"],
    varieties: ["Alphonso", "Kesar", "Banganapalli"],
    steps: [
      "Peel and chop mango",
      "Combine with required ingredients",
      "Blend or cook as needed",
      "Serve chilled or fresh"
    ]
  })),

  // 🟠 OVER-RIPE (BAKING / PROCESSING)
  ...[
    "Mango Cake",
    "Mango Bread",
    "Mango Jam",
    "Mango Preserve",
    "Mango Compote",
    "Mango Syrup",
    "Mango Sauce",
    "Mango Puree",
    "Mango Dessert Cups",
    "Mango Custard Bake",
    "Mango Crumble",
    "Mango Pie",
    "Mango Brownies",
    "Mango Pancake Batter",
    "Mango Waffle Batter",
    "Mango Ice Cream Base",
    "Mango Yogurt Mix",
    "Mango Smoothie Base",
    "Mango Dessert Shots",
    "Mango Trifle",
    "Mango Layered Dessert",
    "Mango Sweet Dip",
    "Mango Frosting",
    "Mango Filling",
    "Mango Dessert Sauce",
    "Mango Compote Dessert",
    "Mango Glaze",
    "Mango Reduction",
    "Mango Spread",
    "Mango Sweet Sauce"
  ].map(name => ({
    name,
    type: "dessert",
    suitableFor: ["overripe"],
    varieties: ["Alphonso", "Kesar"],
    steps: [
      "Mash or puree mango",
      "Add sugar and flavoring",
      "Cook or mix as needed",
      "Use in dessert or serve"
    ]
  }))
];